name: Release Windows

on:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build
        run: python build.windows.py

      - name: Zip build
        run: Compress-Archive -Path dist/Tankobon/* -DestinationPath Tankobon-Windows.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: Tankobon-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
